var age = 25;
console.log(age);
age = 'test';
console.log(age);
age = false;
console.log(age);
age = { name: 'luigi' };
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push('mario');
mixed.push(false);
console.log(mixed);
var ninja;
ninja = { name: 25, age: '52' };
console.log(ninja);
ninja = { name: 'josh', age: 51 };
console.log(ninja);
